[input]
# Input files
gff_file=/Users/samhorsfield/Software/PansimNuc/testing/Zymo_chr18_chr19.gff
fasta_file=/Users/samhorsfield/Software/PansimNuc/testing/Zymo_chr18_chr19.fasta
earlgrey_gff_file=/Users/samhorsfield/Software/PansimNuc/testing/Zymo_EarlGrey_chr18_chr19.gff

[output]
fasta_file=/Users/samhorsfield/Software/PansimNuc/parameter_sweep/exon_selection_pos_low_neg_low_proppos_equal/out.fa
gff_file=/Users/samhorsfield/Software/PansimNuc/parameter_sweep/exon_selection_pos_low_neg_low_proppos_equal/out.gff

[population]
n_individuals=20
n_generations=20
recombination_rate=1e-12
recombination_size_mean=10000.0
recombination_threshold=0.90
max_multiplier_dist=5000

[exons]
mutation_rate=1e-12
selection_distribution=double_exp
selection_lambda1=1e10
selection_lambda2=1e10
selection_cutoff=0.5
duplication_rate=1e-3
deletion_rate=1e-3
inversion_rate=1e-3

[introns]
mutation_rate=1e-12
selection_distribution=uniform
selection_low=-1e-12
selection_high=1e-12
duplication_rate=1e-3
deletion_rate=1e-3
inversion_rate=1e-3

[intergenic]
mutation_rate=1e-12
selection_distribution=uniform
selection_low=-1e-12
selection_high=1e-12
duplication_rate=1e-3
deletion_rate=1e-3
inversion_rate=1e-3
max_duplications=10

[TE-CUT]
mutation_rate=1e-12
selection_distribution=uniform
selection_low=-1e-12
selection_high=1e-12
duplication_rate=1e-3
deletion_rate=1e-3
inversion_rate=1e-3
max_duplications=1
# multipler distribution is gamma
multiplier_rate=1.0
multiplier_scale=1.0

[TE-COPY]
mutation_rate=1e-12
selection_distribution=uniform
selection_low=-1e-12
selection_high=1e-12
duplication_rate=1e-3
deletion_rate=1e-3
inversion_rate=1e-3
max_duplications=1000
# multipler distribution is gamma
multiplier_rate=1.0
multiplier_scale=1.0

[misc]
threads=4
seed=42
verbose=true
