# Example configuration file for PansimNuc
# This file demonstrates the config parser capabilities

[input]
# Input files
gff_file=/home/sam/Software/PansimNuc/testing/synthetic_high_gene_density_coding.gff
fasta_file=/home/sam/Software/PansimNuc/testing/synthetic_high_gene_density.fasta
earlgrey_gff_file=/home/sam/Software/PansimNuc/testing/synthetic_high_gene_density_earlgrey.gff

[output]
outdir=AGR_testing
compress=true

[tracking]
contig=1
start=9501
end=15000
augmentation=true
write_file=false
mutation_rate=1e-50
indel_rate=1e-50
selection_distribution=uniform
selection_low=-1e-15
selection_high=1e-15
duplication_rate=1e-30
deletion_rate=1e-30
inversion_rate=1e-30
#multipler distribution is gamma
multiplier_rate=1.0
multiplier_scale=1.0

[population]
n_individuals=50
n_generations=100
recombination_rate=1e-12
recombination_size_mean=10000.0
recombination_threshold=0.90
max_multiplier_dist=100
population_splits=0
generation_splits=0
migration_rate=0.0
genome_size_penalty_per_bp=0

[exons]
mutation_rate=1e-50
indel_rate=1e-50
selection_distribution=uniform
selection_low=1e-2
selection_high=1e-1
duplication_rate=1e-30
deletion_rate=1e-30
inversion_rate=1e-30

[introns]
mutation_rate=1e-50
indel_rate=1e-50
selection_distribution=uniform
selection_low=-1e-15
selection_high=1e-15
duplication_rate=1e-30
deletion_rate=1e-30
inversion_rate=1e-30

[intergenic]
mutation_rate=1e-50
indel_rate=1e-50
selection_distribution=uniform
selection_low=-1e-15
selection_high=1e-15
duplication_rate=1e-30
deletion_rate=1e-30
inversion_rate=1e-30

[TE-CUT]
mutation_rate=1e-50
indel_rate=1e-50
selection_distribution=uniform
selection_low=-1e-15
selection_high=1e-15
duplication_rate=1e-30
deletion_rate=1e-30
inversion_rate=1e-30
#multipler distribution is gamma
multiplier_rate=1.0
multiplier_scale=1.0

[TE-COPY]
mutation_rate=1e-50
indel_rate=1e-50
selection_distribution=uniform
selection_low=-1e-15
selection_high=1e-15
duplication_rate=2.5e0
deletion_rate=2e0
inversion_rate=1e-30
#multipler distribution is gamma
multiplier_rate=0.1
multiplier_scale=1.0

[misc]
threads=4
seed=42
verbose=true
print_DFE=true
print_all_generations=false
